---
title: "Untitled"
author: "Jiashu Liu"
date: "12/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
library(lubridate)
library(maps)          # for map data
library(ggmap)         # for mapping points on maps
library(RColorBrewer)
library(sjmisc)
library(writexl)
library(geofacet)
```
```{r}
library(readxl)
library(readr)
Total_2019_percent <- read_excel("Total_2019_percent.xlsx", 
    col_types = c("text", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "skip", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric"), 
    na = "N")
Total_2019_numbers <- read_excel("~/Desktop/ACS Data/Total_2019_numbers.xlsx", 
    col_types = c("text", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "skip", "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric"))
county_fips_master <- read_csv("county_fips_master.csv")

```
```{r}
#Total_2019_percent$county_name<-gsub(",.*","",as.character(Total_2019_percent$county_name))

county_2019_percent<-
  Total_2019_percent %>% 
  filter(str_detect(.$county_name, c("County"))) 
```

```{r}
county_fips<-
county_fips_master %>% 
  select(-3) %>% 
  select(-c(5:9)) %>% 
  select(-c(4:7)) 

county_fips$county_name <- paste(county_fips$county_name, county_fips$state_name, sep=", ")

county_fips %>% 
  select(-3)
```

```{r}
fips_2019_percent<-
Total_2019_percent %>% 
  left_join(county_fips, by = "county_name") %>% 
  select(fips, everything())
```
```{r}
#write_xlsx(fips_2019_percent, 
           #"/Users/jiashuliu/Desktop/ACS Data/2019_percent.xlsx")
```

```{r}
county_2019_numbers<-
  Total_2019_numbers%>% 
  filter(str_detect(.$county_name, c("County"))) 
```

```{r}
fips_2019_numbers<-
Total_2019_numbers%>% 
  left_join(county_fips, by = "county_name") %>% 
  select(fips, everything())
```
```{r}
#write_xlsx(fips_2019_numbers, 
           #"/Users/jiashuliu/Desktop/ACS Data/2019_numbers.xlsx")
```

```{r}
#bind_rows()
```

